# Generated by Django 5.0.6 on 2024-06-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_reshows'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommendsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentts', to='exam.reshows')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCom', to='exam.users')),
            ],
        ),
    ]
